// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/flowradio.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MusicControlRequest_Command int32

const (
	MusicControlRequest_COMMAND_UNSPECIFIED MusicControlRequest_Command = 0
	MusicControlRequest_PLAY                MusicControlRequest_Command = 1
	MusicControlRequest_PAUSE               MusicControlRequest_Command = 2
	MusicControlRequest_SET_VOLUME          MusicControlRequest_Command = 3
)

// Enum value maps for MusicControlRequest_Command.
var (
	MusicControlRequest_Command_name = map[int32]string{
		0: "COMMAND_UNSPECIFIED",
		1: "PLAY",
		2: "PAUSE",
		3: "SET_VOLUME",
	}
	MusicControlRequest_Command_value = map[string]int32{
		"COMMAND_UNSPECIFIED": 0,
		"PLAY":                1,
		"PAUSE":               2,
		"SET_VOLUME":          3,
	}
)

func (x MusicControlRequest_Command) Enum() *MusicControlRequest_Command {
	p := new(MusicControlRequest_Command)
	*p = x
	return p
}

func (x MusicControlRequest_Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MusicControlRequest_Command) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_flowradio_proto_enumTypes[0].Descriptor()
}

func (MusicControlRequest_Command) Type() protoreflect.EnumType {
	return &file_proto_flowradio_proto_enumTypes[0]
}

func (x MusicControlRequest_Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MusicControlRequest_Command.Descriptor instead.
func (MusicControlRequest_Command) EnumDescriptor() ([]byte, []int) {
	return file_proto_flowradio_proto_rawDescGZIP(), []int{2, 0}
}

type UpdateMessage_UpdateType int32

const (
	UpdateMessage_UPDATE_UNSPECIFIED UpdateMessage_UpdateType = 0
	UpdateMessage_DJ_DECISION        UpdateMessage_UpdateType = 1 // DJ Brain 的核心决策结果
	UpdateMessage_VIRTUAL_COMMENT    UpdateMessage_UpdateType = 2 // 虚拟听众留言
	UpdateMessage_SYSTEM_STATUS      UpdateMessage_UpdateType = 3 // 系统错误/警告
)

// Enum value maps for UpdateMessage_UpdateType.
var (
	UpdateMessage_UpdateType_name = map[int32]string{
		0: "UPDATE_UNSPECIFIED",
		1: "DJ_DECISION",
		2: "VIRTUAL_COMMENT",
		3: "SYSTEM_STATUS",
	}
	UpdateMessage_UpdateType_value = map[string]int32{
		"UPDATE_UNSPECIFIED": 0,
		"DJ_DECISION":        1,
		"VIRTUAL_COMMENT":    2,
		"SYSTEM_STATUS":      3,
	}
)

func (x UpdateMessage_UpdateType) Enum() *UpdateMessage_UpdateType {
	p := new(UpdateMessage_UpdateType)
	*p = x
	return p
}

func (x UpdateMessage_UpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateMessage_UpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_flowradio_proto_enumTypes[1].Descriptor()
}

func (UpdateMessage_UpdateType) Type() protoreflect.EnumType {
	return &file_proto_flowradio_proto_enumTypes[1]
}

func (x UpdateMessage_UpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateMessage_UpdateType.Descriptor instead.
func (UpdateMessage_UpdateType) EnumDescriptor() ([]byte, []int) {
	return file_proto_flowradio_proto_rawDescGZIP(), []int{8, 0}
}

type SystemStatusData_Severity int32

const (
	SystemStatusData_SEVERITY_INFO    SystemStatusData_Severity = 0
	SystemStatusData_SEVERITY_WARNING SystemStatusData_Severity = 1
	SystemStatusData_SEVERITY_ERROR   SystemStatusData_Severity = 2
)

// Enum value maps for SystemStatusData_Severity.
var (
	SystemStatusData_Severity_name = map[int32]string{
		0: "SEVERITY_INFO",
		1: "SEVERITY_WARNING",
		2: "SEVERITY_ERROR",
	}
	SystemStatusData_Severity_value = map[string]int32{
		"SEVERITY_INFO":    0,
		"SEVERITY_WARNING": 1,
		"SEVERITY_ERROR":   2,
	}
)

func (x SystemStatusData_Severity) Enum() *SystemStatusData_Severity {
	p := new(SystemStatusData_Severity)
	*p = x
	return p
}

func (x SystemStatusData_Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SystemStatusData_Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_flowradio_proto_enumTypes[2].Descriptor()
}

func (SystemStatusData_Severity) Type() protoreflect.EnumType {
	return &file_proto_flowradio_proto_enumTypes[2]
}

func (x SystemStatusData_Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SystemStatusData_Severity.Descriptor instead.
func (SystemStatusData_Severity) EnumDescriptor() ([]byte, []int) {
	return file_proto_flowradio_proto_rawDescGZIP(), []int{10, 0}
}

// ConversationMessage: 单条对话记录 (用于历史)
type ConversationMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`       // "user", "assistant", 或 "system"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // 对话内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationMessage) Reset() {
	*x = ConversationMessage{}
	mi := &file_proto_flowradio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationMessage) ProtoMessage() {}

func (x *ConversationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flowradio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationMessage.ProtoReflect.Descriptor instead.
func (*ConversationMessage) Descriptor() ([]byte, []int) {
	return file_proto_flowradio_proto_rawDescGZIP(), []int{0}
}

func (x *ConversationMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ConversationMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// PromptRequest: 听众来电/Prompt
type PromptRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	PromptText   string                 `protobuf:"bytes,1,opt,name=prompt_text,json=promptText,proto3" json:"prompt_text,omitempty"`
	ContextScene string                 `protobuf:"bytes,2,opt,name=context_scene,json=contextScene,proto3" json:"context_scene,omitempty"`
	// 修正: 多轮对话历史
	ConversationHistory []*ConversationMessage `protobuf:"bytes,3,rep,name=conversation_history,json=conversationHistory,proto3" json:"conversation_history,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PromptRequest) Reset() {
	*x = PromptRequest{}
	mi := &file_proto_flowradio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptRequest) ProtoMessage() {}

func (x *PromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flowradio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptRequest.ProtoReflect.Descriptor instead.
func (*PromptRequest) Descriptor() ([]byte, []int) {
	return file_proto_flowradio_proto_rawDescGZIP(), []int{1}
}

func (x *PromptRequest) GetPromptText() string {
	if x != nil {
		return x.PromptText
	}
	return ""
}

func (x *PromptRequest) GetContextScene() string {
	if x != nil {
		return x.ContextScene
	}
	return ""
}

func (x *PromptRequest) GetConversationHistory() []*ConversationMessage {
	if x != nil {
		return x.ConversationHistory
	}
	return nil
}

// MusicControlRequest: 播放/音量控制
type MusicControlRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Command       MusicControlRequest_Command `protobuf:"varint,1,opt,name=command,proto3,enum=flowradio.MusicControlRequest_Command" json:"command,omitempty"`
	Value         int32                       `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MusicControlRequest) Reset() {
	*x = MusicControlRequest{}
	mi := &file_proto_flowradio_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MusicControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MusicControlRequest) ProtoMessage() {}

func (x *MusicControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flowradio_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MusicControlRequest.ProtoReflect.Descriptor instead.
func (*MusicControlRequest) Descriptor() ([]byte, []int) {
	return file_proto_flowradio_proto_rawDescGZIP(), []int{2}
}

func (x *MusicControlRequest) GetCommand() MusicControlRequest_Command {
	if x != nil {
		return x.Command
	}
	return MusicControlRequest_COMMAND_UNSPECIFIED
}

func (x *MusicControlRequest) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// HostConfigRequest: 主持人配置
type HostConfigRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HostId          string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	PersonalityType string                 `protobuf:"bytes,2,opt,name=personality_type,json=personalityType,proto3" json:"personality_type,omitempty"`
	VoiceId         string                 `protobuf:"bytes,3,opt,name=voice_id,json=voiceId,proto3" json:"voice_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HostConfigRequest) Reset() {
	*x = HostConfigRequest{}
	mi := &file_proto_flowradio_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostConfigRequest) ProtoMessage() {}

func (x *HostConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flowradio_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostConfigRequest.ProtoReflect.Descriptor instead.
func (*HostConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_flowradio_proto_rawDescGZIP(), []int{3}
}

func (x *HostConfigRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *HostConfigRequest) GetPersonalityType() string {
	if x != nil {
		return x.PersonalityType
	}
	return ""
}

func (x *HostConfigRequest) GetVoiceId() string {
	if x != nil {
		return x.VoiceId
	}
	return ""
}

// StreamRequest: 客户端请求开始接收更新
type StreamRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClientSessionId string                 `protobuf:"bytes,1,opt,name=client_session_id,json=clientSessionId,proto3" json:"client_session_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_proto_flowradio_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flowradio_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_flowradio_proto_rawDescGZIP(), []int{4}
}

func (x *StreamRequest) GetClientSessionId() string {
	if x != nil {
		return x.ClientSessionId
	}
	return ""
}

// =========================================================================
// 3. 响应数据结构 (Server Response Messages)
// =========================================================================
type PromptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptResponse) Reset() {
	*x = PromptResponse{}
	mi := &file_proto_flowradio_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptResponse) ProtoMessage() {}

func (x *PromptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flowradio_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptResponse.ProtoReflect.Descriptor instead.
func (*PromptResponse) Descriptor() ([]byte, []int) {
	return file_proto_flowradio_proto_rawDescGZIP(), []int{5}
}

func (x *PromptResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PromptResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ControlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlResponse) Reset() {
	*x = ControlResponse{}
	mi := &file_proto_flowradio_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlResponse) ProtoMessage() {}

func (x *ControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flowradio_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlResponse.ProtoReflect.Descriptor instead.
func (*ControlResponse) Descriptor() ([]byte, []int) {
	return file_proto_flowradio_proto_rawDescGZIP(), []int{6}
}

func (x *ControlResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ControlResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigResponse) Reset() {
	*x = ConfigResponse{}
	mi := &file_proto_flowradio_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResponse) ProtoMessage() {}

func (x *ConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flowradio_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResponse.ProtoReflect.Descriptor instead.
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_flowradio_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// UpdateMessage: 后端向前端推送的实时更新数据 (核心)
type UpdateMessage struct {
	state       protoimpl.MessageState   `protogen:"open.v1"`
	Type        UpdateMessage_UpdateType `protobuf:"varint,1,opt,name=type,proto3,enum=flowradio.UpdateMessage_UpdateType" json:"type,omitempty"`
	TimestampMs int64                    `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	// 使用 oneof 确保每次只传输一种类型的负载
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*UpdateMessage_DecisionData
	//	*UpdateMessage_VirtualCommentText
	//	*UpdateMessage_SystemStatusData
	Payload       isUpdateMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessage) Reset() {
	*x = UpdateMessage{}
	mi := &file_proto_flowradio_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessage) ProtoMessage() {}

func (x *UpdateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flowradio_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessage.ProtoReflect.Descriptor instead.
func (*UpdateMessage) Descriptor() ([]byte, []int) {
	return file_proto_flowradio_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateMessage) GetType() UpdateMessage_UpdateType {
	if x != nil {
		return x.Type
	}
	return UpdateMessage_UPDATE_UNSPECIFIED
}

func (x *UpdateMessage) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *UpdateMessage) GetPayload() isUpdateMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UpdateMessage) GetDecisionData() *DJBrainDecision {
	if x != nil {
		if x, ok := x.Payload.(*UpdateMessage_DecisionData); ok {
			return x.DecisionData
		}
	}
	return nil
}

func (x *UpdateMessage) GetVirtualCommentText() string {
	if x != nil {
		if x, ok := x.Payload.(*UpdateMessage_VirtualCommentText); ok {
			return x.VirtualCommentText
		}
	}
	return ""
}

func (x *UpdateMessage) GetSystemStatusData() *SystemStatusData {
	if x != nil {
		if x, ok := x.Payload.(*UpdateMessage_SystemStatusData); ok {
			return x.SystemStatusData
		}
	}
	return nil
}

type isUpdateMessage_Payload interface {
	isUpdateMessage_Payload()
}

type UpdateMessage_DecisionData struct {
	DecisionData *DJBrainDecision `protobuf:"bytes,3,opt,name=decision_data,json=decisionData,proto3,oneof"` // 替换 HostSpeechData 和 GenreChangeData
}

type UpdateMessage_VirtualCommentText struct {
	VirtualCommentText string `protobuf:"bytes,4,opt,name=virtual_comment_text,json=virtualCommentText,proto3,oneof"`
}

type UpdateMessage_SystemStatusData struct {
	SystemStatusData *SystemStatusData `protobuf:"bytes,5,opt,name=system_status_data,json=systemStatusData,proto3,oneof"`
}

func (*UpdateMessage_DecisionData) isUpdateMessage_Payload() {}

func (*UpdateMessage_VirtualCommentText) isUpdateMessage_Payload() {}

func (*UpdateMessage_SystemStatusData) isUpdateMessage_Payload() {}

// DJBrainDecision: DJ Brain 的核心决策 (包含脚本、音乐、记忆)
type DJBrainDecision struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1. 主持人脚本 (要显示和播放的)
	DjScript string `protobuf:"bytes,1,opt,name=dj_script,json=djScript,proto3" json:"dj_script,omitempty"`
	// 2. TTS 音频数据 (bytes)
	AudioDataBytes []byte `protobuf:"bytes,2,opt,name=audio_data_bytes,json=audioDataBytes,proto3" json:"audio_data_bytes,omitempty"`
	// 3. 音乐风格和权重 (给 Magenta 的指令)
	MusicPrompts    []string  `protobuf:"bytes,3,rep,name=music_prompts,json=musicPrompts,proto3" json:"music_prompts,omitempty"`
	TrainingWeights []float32 `protobuf:"fixed32,4,rep,packed,name=training_weights,json=trainingWeights,proto3" json:"training_weights,omitempty"` // 权重，避免与 proto 关键词冲突
	// 4. LLM 决策信息
	ActionReason string `protobuf:"bytes,5,opt,name=action_reason,json=actionReason,proto3" json:"action_reason,omitempty"`
	// 5. 新的对话记忆 (新的摘要/状态)
	NewConversationMemory string `protobuf:"bytes,6,opt,name=new_conversation_memory,json=newConversationMemory,proto3" json:"new_conversation_memory,omitempty"`
	// 6. UI 风格推荐
	StyleRecommendation string `protobuf:"bytes,7,opt,name=style_recommendation,json=styleRecommendation,proto3" json:"style_recommendation,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DJBrainDecision) Reset() {
	*x = DJBrainDecision{}
	mi := &file_proto_flowradio_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DJBrainDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DJBrainDecision) ProtoMessage() {}

func (x *DJBrainDecision) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flowradio_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DJBrainDecision.ProtoReflect.Descriptor instead.
func (*DJBrainDecision) Descriptor() ([]byte, []int) {
	return file_proto_flowradio_proto_rawDescGZIP(), []int{9}
}

func (x *DJBrainDecision) GetDjScript() string {
	if x != nil {
		return x.DjScript
	}
	return ""
}

func (x *DJBrainDecision) GetAudioDataBytes() []byte {
	if x != nil {
		return x.AudioDataBytes
	}
	return nil
}

func (x *DJBrainDecision) GetMusicPrompts() []string {
	if x != nil {
		return x.MusicPrompts
	}
	return nil
}

func (x *DJBrainDecision) GetTrainingWeights() []float32 {
	if x != nil {
		return x.TrainingWeights
	}
	return nil
}

func (x *DJBrainDecision) GetActionReason() string {
	if x != nil {
		return x.ActionReason
	}
	return ""
}

func (x *DJBrainDecision) GetNewConversationMemory() string {
	if x != nil {
		return x.NewConversationMemory
	}
	return ""
}

func (x *DJBrainDecision) GetStyleRecommendation() string {
	if x != nil {
		return x.StyleRecommendation
	}
	return ""
}

// SystemStatusData: 系统状态/错误数据
type SystemStatusData struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Severity      SystemStatusData_Severity `protobuf:"varint,1,opt,name=severity,proto3,enum=flowradio.SystemStatusData_Severity" json:"severity,omitempty"`
	Message       string                    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemStatusData) Reset() {
	*x = SystemStatusData{}
	mi := &file_proto_flowradio_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStatusData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStatusData) ProtoMessage() {}

func (x *SystemStatusData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flowradio_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStatusData.ProtoReflect.Descriptor instead.
func (*SystemStatusData) Descriptor() ([]byte, []int) {
	return file_proto_flowradio_proto_rawDescGZIP(), []int{10}
}

func (x *SystemStatusData) GetSeverity() SystemStatusData_Severity {
	if x != nil {
		return x.Severity
	}
	return SystemStatusData_SEVERITY_INFO
}

func (x *SystemStatusData) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_flowradio_proto protoreflect.FileDescriptor

const file_proto_flowradio_proto_rawDesc = "" +
	"\n" +
	"\x15proto/flowradio.proto\x12\tflowradio\"C\n" +
	"\x13ConversationMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xa8\x01\n" +
	"\rPromptRequest\x12\x1f\n" +
	"\vprompt_text\x18\x01 \x01(\tR\n" +
	"promptText\x12#\n" +
	"\rcontext_scene\x18\x02 \x01(\tR\fcontextScene\x12Q\n" +
	"\x14conversation_history\x18\x03 \x03(\v2\x1e.flowradio.ConversationMessageR\x13conversationHistory\"\xb6\x01\n" +
	"\x13MusicControlRequest\x12@\n" +
	"\acommand\x18\x01 \x01(\x0e2&.flowradio.MusicControlRequest.CommandR\acommand\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\"G\n" +
	"\aCommand\x12\x17\n" +
	"\x13COMMAND_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04PLAY\x10\x01\x12\t\n" +
	"\x05PAUSE\x10\x02\x12\x0e\n" +
	"\n" +
	"SET_VOLUME\x10\x03\"r\n" +
	"\x11HostConfigRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12)\n" +
	"\x10personality_type\x18\x02 \x01(\tR\x0fpersonalityType\x12\x19\n" +
	"\bvoice_id\x18\x03 \x01(\tR\avoiceId\";\n" +
	"\rStreamRequest\x12*\n" +
	"\x11client_session_id\x18\x01 \x01(\tR\x0fclientSessionId\"D\n" +
	"\x0ePromptResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"E\n" +
	"\x0fControlResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"D\n" +
	"\x0eConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x99\x03\n" +
	"\rUpdateMessage\x127\n" +
	"\x04type\x18\x01 \x01(\x0e2#.flowradio.UpdateMessage.UpdateTypeR\x04type\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12A\n" +
	"\rdecision_data\x18\x03 \x01(\v2\x1a.flowradio.DJBrainDecisionH\x00R\fdecisionData\x122\n" +
	"\x14virtual_comment_text\x18\x04 \x01(\tH\x00R\x12virtualCommentText\x12K\n" +
	"\x12system_status_data\x18\x05 \x01(\v2\x1b.flowradio.SystemStatusDataH\x00R\x10systemStatusData\"]\n" +
	"\n" +
	"UpdateType\x12\x16\n" +
	"\x12UPDATE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vDJ_DECISION\x10\x01\x12\x13\n" +
	"\x0fVIRTUAL_COMMENT\x10\x02\x12\x11\n" +
	"\rSYSTEM_STATUS\x10\x03B\t\n" +
	"\apayload\"\xb8\x02\n" +
	"\x0fDJBrainDecision\x12\x1b\n" +
	"\tdj_script\x18\x01 \x01(\tR\bdjScript\x12(\n" +
	"\x10audio_data_bytes\x18\x02 \x01(\fR\x0eaudioDataBytes\x12#\n" +
	"\rmusic_prompts\x18\x03 \x03(\tR\fmusicPrompts\x12)\n" +
	"\x10training_weights\x18\x04 \x03(\x02R\x0ftrainingWeights\x12#\n" +
	"\raction_reason\x18\x05 \x01(\tR\factionReason\x126\n" +
	"\x17new_conversation_memory\x18\x06 \x01(\tR\x15newConversationMemory\x121\n" +
	"\x14style_recommendation\x18\a \x01(\tR\x13styleRecommendation\"\xb7\x01\n" +
	"\x10SystemStatusData\x12@\n" +
	"\bseverity\x18\x01 \x01(\x0e2$.flowradio.SystemStatusData.SeverityR\bseverity\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"G\n" +
	"\bSeverity\x12\x11\n" +
	"\rSEVERITY_INFO\x10\x00\x12\x14\n" +
	"\x10SEVERITY_WARNING\x10\x01\x12\x12\n" +
	"\x0eSEVERITY_ERROR\x10\x022\xc3\x02\n" +
	"\x10FlowRadioService\x12I\n" +
	"\x10HandleUserPrompt\x12\x18.flowradio.PromptRequest\x1a\x19.flowradio.PromptResponse\"\x00\x12O\n" +
	"\x0fSetMusicControl\x12\x1e.flowradio.MusicControlRequest\x1a\x1a.flowradio.ControlResponse\"\x00\x12J\n" +
	"\rSetHostConfig\x12\x1c.flowradio.HostConfigRequest\x1a\x19.flowradio.ConfigResponse\"\x00\x12G\n" +
	"\rStreamUpdates\x12\x18.flowradio.StreamRequest\x1a\x18.flowradio.UpdateMessage\"\x000\x01B\x19Z\x17flowradio/backend/protob\x06proto3"

var (
	file_proto_flowradio_proto_rawDescOnce sync.Once
	file_proto_flowradio_proto_rawDescData []byte
)

func file_proto_flowradio_proto_rawDescGZIP() []byte {
	file_proto_flowradio_proto_rawDescOnce.Do(func() {
		file_proto_flowradio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_flowradio_proto_rawDesc), len(file_proto_flowradio_proto_rawDesc)))
	})
	return file_proto_flowradio_proto_rawDescData
}

var file_proto_flowradio_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_flowradio_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_flowradio_proto_goTypes = []any{
	(MusicControlRequest_Command)(0), // 0: flowradio.MusicControlRequest.Command
	(UpdateMessage_UpdateType)(0),    // 1: flowradio.UpdateMessage.UpdateType
	(SystemStatusData_Severity)(0),   // 2: flowradio.SystemStatusData.Severity
	(*ConversationMessage)(nil),      // 3: flowradio.ConversationMessage
	(*PromptRequest)(nil),            // 4: flowradio.PromptRequest
	(*MusicControlRequest)(nil),      // 5: flowradio.MusicControlRequest
	(*HostConfigRequest)(nil),        // 6: flowradio.HostConfigRequest
	(*StreamRequest)(nil),            // 7: flowradio.StreamRequest
	(*PromptResponse)(nil),           // 8: flowradio.PromptResponse
	(*ControlResponse)(nil),          // 9: flowradio.ControlResponse
	(*ConfigResponse)(nil),           // 10: flowradio.ConfigResponse
	(*UpdateMessage)(nil),            // 11: flowradio.UpdateMessage
	(*DJBrainDecision)(nil),          // 12: flowradio.DJBrainDecision
	(*SystemStatusData)(nil),         // 13: flowradio.SystemStatusData
}
var file_proto_flowradio_proto_depIdxs = []int32{
	3,  // 0: flowradio.PromptRequest.conversation_history:type_name -> flowradio.ConversationMessage
	0,  // 1: flowradio.MusicControlRequest.command:type_name -> flowradio.MusicControlRequest.Command
	1,  // 2: flowradio.UpdateMessage.type:type_name -> flowradio.UpdateMessage.UpdateType
	12, // 3: flowradio.UpdateMessage.decision_data:type_name -> flowradio.DJBrainDecision
	13, // 4: flowradio.UpdateMessage.system_status_data:type_name -> flowradio.SystemStatusData
	2,  // 5: flowradio.SystemStatusData.severity:type_name -> flowradio.SystemStatusData.Severity
	4,  // 6: flowradio.FlowRadioService.HandleUserPrompt:input_type -> flowradio.PromptRequest
	5,  // 7: flowradio.FlowRadioService.SetMusicControl:input_type -> flowradio.MusicControlRequest
	6,  // 8: flowradio.FlowRadioService.SetHostConfig:input_type -> flowradio.HostConfigRequest
	7,  // 9: flowradio.FlowRadioService.StreamUpdates:input_type -> flowradio.StreamRequest
	8,  // 10: flowradio.FlowRadioService.HandleUserPrompt:output_type -> flowradio.PromptResponse
	9,  // 11: flowradio.FlowRadioService.SetMusicControl:output_type -> flowradio.ControlResponse
	10, // 12: flowradio.FlowRadioService.SetHostConfig:output_type -> flowradio.ConfigResponse
	11, // 13: flowradio.FlowRadioService.StreamUpdates:output_type -> flowradio.UpdateMessage
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_flowradio_proto_init() }
func file_proto_flowradio_proto_init() {
	if File_proto_flowradio_proto != nil {
		return
	}
	file_proto_flowradio_proto_msgTypes[8].OneofWrappers = []any{
		(*UpdateMessage_DecisionData)(nil),
		(*UpdateMessage_VirtualCommentText)(nil),
		(*UpdateMessage_SystemStatusData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_flowradio_proto_rawDesc), len(file_proto_flowradio_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_flowradio_proto_goTypes,
		DependencyIndexes: file_proto_flowradio_proto_depIdxs,
		EnumInfos:         file_proto_flowradio_proto_enumTypes,
		MessageInfos:      file_proto_flowradio_proto_msgTypes,
	}.Build()
	File_proto_flowradio_proto = out.File
	file_proto_flowradio_proto_goTypes = nil
	file_proto_flowradio_proto_depIdxs = nil
}
