// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/flowradio.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FlowRadioService_HandleUserPrompt_FullMethodName = "/flowradio.FlowRadioService/HandleUserPrompt"
	FlowRadioService_SetMusicControl_FullMethodName  = "/flowradio.FlowRadioService/SetMusicControl"
	FlowRadioService_SetHostConfig_FullMethodName    = "/flowradio.FlowRadioService/SetHostConfig"
	FlowRadioService_StreamUpdates_FullMethodName    = "/flowradio.FlowRadioService/StreamUpdates"
)

// FlowRadioServiceClient is the client API for FlowRadioService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =========================================================================
//  1. 服务定义 (Service Definition)
//     由 Go 后端实现的 gRPC 服务接口
//
// =========================================================================
type FlowRadioServiceClient interface {
	// 1. 用户来电/Prompt处理 (Client -> Server)
	// 客户端发送 Prompt，后端返回确认信息
	HandleUserPrompt(ctx context.Context, in *PromptRequest, opts ...grpc.CallOption) (*PromptResponse, error)
	// 2. 音乐控制指令 (Client -> Server)
	SetMusicControl(ctx context.Context, in *MusicControlRequest, opts ...grpc.CallOption) (*ControlResponse, error)
	// 3. 配置指令 (Client -> Server)
	SetHostConfig(ctx context.Context, in *HostConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error)
	// 4. 状态与脚本的实时推送 (Server Streaming)
	// 后端持续向前端推送所有实时更新
	StreamUpdates(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UpdateMessage], error)
}

type flowRadioServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlowRadioServiceClient(cc grpc.ClientConnInterface) FlowRadioServiceClient {
	return &flowRadioServiceClient{cc}
}

func (c *flowRadioServiceClient) HandleUserPrompt(ctx context.Context, in *PromptRequest, opts ...grpc.CallOption) (*PromptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromptResponse)
	err := c.cc.Invoke(ctx, FlowRadioService_HandleUserPrompt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flowRadioServiceClient) SetMusicControl(ctx context.Context, in *MusicControlRequest, opts ...grpc.CallOption) (*ControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlResponse)
	err := c.cc.Invoke(ctx, FlowRadioService_SetMusicControl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flowRadioServiceClient) SetHostConfig(ctx context.Context, in *HostConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, FlowRadioService_SetHostConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flowRadioServiceClient) StreamUpdates(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UpdateMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FlowRadioService_ServiceDesc.Streams[0], FlowRadioService_StreamUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, UpdateMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FlowRadioService_StreamUpdatesClient = grpc.ServerStreamingClient[UpdateMessage]

// FlowRadioServiceServer is the server API for FlowRadioService service.
// All implementations must embed UnimplementedFlowRadioServiceServer
// for forward compatibility.
//
// =========================================================================
//  1. 服务定义 (Service Definition)
//     由 Go 后端实现的 gRPC 服务接口
//
// =========================================================================
type FlowRadioServiceServer interface {
	// 1. 用户来电/Prompt处理 (Client -> Server)
	// 客户端发送 Prompt，后端返回确认信息
	HandleUserPrompt(context.Context, *PromptRequest) (*PromptResponse, error)
	// 2. 音乐控制指令 (Client -> Server)
	SetMusicControl(context.Context, *MusicControlRequest) (*ControlResponse, error)
	// 3. 配置指令 (Client -> Server)
	SetHostConfig(context.Context, *HostConfigRequest) (*ConfigResponse, error)
	// 4. 状态与脚本的实时推送 (Server Streaming)
	// 后端持续向前端推送所有实时更新
	StreamUpdates(*StreamRequest, grpc.ServerStreamingServer[UpdateMessage]) error
	mustEmbedUnimplementedFlowRadioServiceServer()
}

// UnimplementedFlowRadioServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFlowRadioServiceServer struct{}

func (UnimplementedFlowRadioServiceServer) HandleUserPrompt(context.Context, *PromptRequest) (*PromptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleUserPrompt not implemented")
}
func (UnimplementedFlowRadioServiceServer) SetMusicControl(context.Context, *MusicControlRequest) (*ControlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetMusicControl not implemented")
}
func (UnimplementedFlowRadioServiceServer) SetHostConfig(context.Context, *HostConfigRequest) (*ConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetHostConfig not implemented")
}
func (UnimplementedFlowRadioServiceServer) StreamUpdates(*StreamRequest, grpc.ServerStreamingServer[UpdateMessage]) error {
	return status.Errorf(codes.Unimplemented, "method StreamUpdates not implemented")
}
func (UnimplementedFlowRadioServiceServer) mustEmbedUnimplementedFlowRadioServiceServer() {}
func (UnimplementedFlowRadioServiceServer) testEmbeddedByValue()                          {}

// UnsafeFlowRadioServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlowRadioServiceServer will
// result in compilation errors.
type UnsafeFlowRadioServiceServer interface {
	mustEmbedUnimplementedFlowRadioServiceServer()
}

func RegisterFlowRadioServiceServer(s grpc.ServiceRegistrar, srv FlowRadioServiceServer) {
	// If the following call pancis, it indicates UnimplementedFlowRadioServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FlowRadioService_ServiceDesc, srv)
}

func _FlowRadioService_HandleUserPrompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowRadioServiceServer).HandleUserPrompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlowRadioService_HandleUserPrompt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowRadioServiceServer).HandleUserPrompt(ctx, req.(*PromptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlowRadioService_SetMusicControl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MusicControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowRadioServiceServer).SetMusicControl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlowRadioService_SetMusicControl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowRadioServiceServer).SetMusicControl(ctx, req.(*MusicControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlowRadioService_SetHostConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowRadioServiceServer).SetHostConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlowRadioService_SetHostConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowRadioServiceServer).SetHostConfig(ctx, req.(*HostConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlowRadioService_StreamUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FlowRadioServiceServer).StreamUpdates(m, &grpc.GenericServerStream[StreamRequest, UpdateMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FlowRadioService_StreamUpdatesServer = grpc.ServerStreamingServer[UpdateMessage]

// FlowRadioService_ServiceDesc is the grpc.ServiceDesc for FlowRadioService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlowRadioService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flowradio.FlowRadioService",
	HandlerType: (*FlowRadioServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleUserPrompt",
			Handler:    _FlowRadioService_HandleUserPrompt_Handler,
		},
		{
			MethodName: "SetMusicControl",
			Handler:    _FlowRadioService_SetMusicControl_Handler,
		},
		{
			MethodName: "SetHostConfig",
			Handler:    _FlowRadioService_SetHostConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamUpdates",
			Handler:       _FlowRadioService_StreamUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/flowradio.proto",
}
